//
// Goal: Reduce the size of the downloaded file from uniprot by extracting only 4 elements for each protein.
//
// ID: ID code, usually as a 6 character (in some organisms it could be more)
// OS: Full name of the organism 
// KW: The keyword where we expect to find PTMs
// FT: The features of the protein where we also expect to find PTM. Only in: MOD_RES ; CROSSLINK; and LIPID
//
// File I / O in C++ works very similarly to normal I / O (with a few minor added complexities).
// There are 3 basic file I / O classes in C++: 
// 1. ifstream(derived from istream), 
// 2. ofstream(derived from ostream), and 
// 3. fstream(derived from iostream).
// 
// These classes do file input, output, and input / output respectively.
//
// To use the file I / O classes, you will need to load the fstream header.
// To read and handle string from the input file we include string.
// We also include vector and algorithm in order to search for 6 desired features.
//

#include <iostream>   // Usual C++ library that need to be included for many simple tasks such as std::
#include <fstream>    // fstream allows both reading and writing files (input and output I/O)
#include <string>     // Necessary to read string from the input file
#include <vector>     // Necessary to write vector


int main() {

    //
    // Create an instance of ifstream class to read the name of the downloaded file from UniProt.
    // The name of the file is recorded in INPUT.txt 
    // The INPUT.txt has been generated by Download_Data_From_UniProt() function in R module.
    //
    std::ifstream infile("/home/payman/Projects/PEIMAN2DBUpd/INPUT.txt");
    std::string UniProtInputFileName;
    if ( infile.good() ) {
        std::cout << "Reading input file name ... \n";
        std::getline(infile, UniProtInputFileName);
    }


    //
    // Create an instance of ifstream class to read the name of the output file. 
    // This output file indicates what should the name of the reduced file be.
    // The name of the file is recorded in OUTPUT.txt 
    // The OUTPUT.txt has been generated by Download_Data_From_UniProt() function in R module.
    //
    std::ifstream oufile("/home/payman/Projects/PEIMAN2DBUpd/OUTPUT.txt");
    std::string UniProtOutputFileName;
    if ( oufile.good() ) {
        std::cout << "Reading output file name ... \n";
        std::getline(oufile, UniProtOutputFileName);
    }


    //
    // Create two instances of ifstream and ofstream classes to read and write the files.
    //
    std::ifstream input_file ( UniProtInputFileName.c_str()  );
    std::ofstream output_file( UniProtOutputFileName.c_str() );
    std::cout << "Input and output files are created. \n";


    //
    // Read all the lines and extract the 6 desired features for each protein.
    // When we write the information in the reduced file, we add the keyword HERE to each of the
    // 6 desired names {ID, AC, OS, KW, FT, and CC}. This helps later in Extract_Elements_From_Protein_List()
    // function in R module when we read from the output file.
    //

    std::cout << "IStart reading the file and reducing the size... \n";
    while ( input_file ) {
      
        //
        // read stuff from the file into a string and check if we need to keep it.
        //
        std::string strInput;
        std::getline(input_file, strInput);

        if (strInput.substr(0, 2) == "AC") {
            output_file << "ACHERE" << strInput << '\n';
        }

        //if (strInput.substr(0, 2) == "ID") {
            //output_file << "IDHERE" << strInput << '\n';
        //}

        if (strInput.substr(0, 2) == "OS") {
            output_file << "OSHERE" << strInput << '\n';
        }

        if (strInput.substr(0, 2) == "KW") {
            output_file << "KWHERE" << strInput << '\n';
        }

        if (strInput.substr(0, 2) == "FT") {
            output_file << "FTHERE" << strInput << '\n';
        }

        //if (strInput.substr(0, 2) == "CC") {
            //output_file << "CCHERE" << strInput << '\n';
        //}

        if (strInput.substr(0, 2) == "//") {
            output_file << "_" << strInput << "_" << '\n';
        }
    }

    std::cout << "DONE! check directory /home/payman/Projects/PEIMAN2DBUpd/DBLog/  \n";

    return 0;
}
